#!/bin/sh
# SessionStart hook: a waking agent is handed the work queue, not a blank repo.
#
# GENERATED by `uel harness install --target claude-code` from uel 0.6.0.
# Do not hand-edit — regenerate; `uel harness check` fails if this drifts.
#
# stdout lands in the session's context, so the first thing the agent knows is
# where the highest-value stale work is. All this file knows about the harness:
# stdout is context and CLAUDE_PROJECT_DIR names the repository root.
#
# Never fatal, never noisy: a repo whose tooling is missing must still open.
set -u

REPO="${CLAUDE_PROJECT_DIR:-$(pwd)}"
MANIFEST="uel.toml"
# The brief, best rung first. Rungs are PROBED against the kernel actually
# installed here, so a subcommand this adapter was generated before — or after —
# is used when present and silently skipped when not. Detect, never assume.
LADDER='stale --rank|agenda|stale'
OPTIONAL='doctor'

cd "$REPO" 2>/dev/null || exit 0
PYTHONPATH="$REPO${PYTHONPATH:+:$PYTHONPATH}"
export PYTHONPATH

# Installed entry point, else the module — including a checkout that was never
# pip-installed. If neither answers, stay out of the way entirely.
if command -v uel >/dev/null 2>&1 && uel --version >/dev/null 2>&1; then
  UEL="uel"
elif python3 -m uel --version >/dev/null 2>&1; then
  UEL="python3 -m uel"
else
  exit 0
fi

supported() { # supported <subcommand> [<required-option>]
  $UEL "$1" --help >/dev/null 2>&1 || return 1
  [ "$#" -lt 2 ] || $UEL "$1" --help 2>&1 | grep -q -- "$2"
}

RUNG=''
OLDIFS=$IFS
IFS='|'
# shellcheck disable=SC2086
set -- $LADDER
IFS=$OLDIFS
for rung in "$@"; do
  [ -n "$rung" ] || continue
  # shellcheck disable=SC2086
  if supported $rung; then RUNG=$rung; break; fi
done
[ -n "$RUNG" ] || exit 0

PROJECTS=$(find "$REPO" -maxdepth 4 -name "$MANIFEST" -not -path '*/.*' 2>/dev/null |
  awk -F/ '{print NF"\t"$0}' | sort -n | cut -f2- | head -n 3)
[ -n "$PROJECTS" ] || exit 0

echo "== uel 0.6.0 — the standing work queue, highest value first =="
printf '%s\n' "$PROJECTS" | while IFS= read -r manifest; do
  [ -n "$manifest" ] || continue
  dir=$(dirname "$manifest")
  rel=${dir#"$REPO"/}
  [ "$rel" != "$dir" ] || rel='.'
  echo ""
  echo "-- $rel   \$ $UEL $RUNG $rel"
  # shellcheck disable=SC2086
  $UEL $RUNG "$dir" 2>&1 | sed 's/^/   /' | head -n 14
done

for c in $OPTIONAL; do
  if supported "$c"; then echo ""; echo "also available in this kernel: \$ $UEL $c"; fi
done

echo ""
echo "loop: uel check -> fix every diagnostic -> uel build -> record judgment WITH doubts -> uel fmt -> commit sources AND uel.lock"
echo "orient: \$ $UEL agent   ·   operating skill: .claude/skills/uel-engineer/SKILL.md"
exit 0
