#!/usr/bin/env python3
"""PostToolUse hook: the compile gate, fired on every edit to a model source.

GENERATED by `uel harness install --target claude-code` from uel 0.6.0.
Do not hand-edit — regenerate; `uel harness check` fails if this drifts.

Compile time here is seconds and needs no solver, which makes it cheap enough to
run on a keystroke instead of only at merge. On errors this exits 2, so the
diagnostics land back in the context of the agent that just made the edit — a
dropped unit or a broken fence is corrected in the same breath it was written.

All this file knows about the harness: hook JSON arrives on stdin, exit 0
allows, exit 2 feeds stderr back to the model, CLAUDE_PROJECT_DIR names the
repository root. Everything it knows about the tool was substituted in.
Stdlib only, and a silent no-op when the kernel is absent or the edit is not
ours: a repository must never be *broken* by its own tooling.
"""

import json, os, subprocess, sys
from pathlib import Path

WATCHED = tuple([".uel", "uel.toml"])
MANIFEST = "uel.toml"
CHECK_ARGV = ["check", "--json"]
MAX_SHOWN = 12

def enclosing_project(edited, repo):
    """Nearest ancestor of the edited file holding a manifest, at or under the repo
    root. A repository may hold several projects; grade only the one touched."""
    for cand in (edited.parent, *edited.parents):
        if (cand / MANIFEST).is_file(): return cand
        if cand == repo: break
    return None

def kernel(repo):
    """How to invoke the tool *here*: the installed entry point, or the module —
    including a source checkout that was never pip-installed (repo on PYTHONPATH).
    Detect, never assume."""
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join([str(repo), env.get("PYTHONPATH", "")]).rstrip(os.pathsep)
    for argv in (["uel"], [sys.executable, "-m", "uel"]):
        try:
            r = subprocess.run(argv + ["--version"], capture_output=True, cwd=repo, env=env, timeout=30)
        except (OSError, subprocess.SubprocessError):
            continue
        if r.returncode == 0: return argv, env
    return None

def report(errors, edited, project, argv):
    out = [f"{argv[-1]} {CHECK_ARGV[0]}: {len(errors)} error(s) after editing {edited.name} — "
           f"compile time gates runtime, so fix these before building or committing."]
    for d in errors[:MAX_SHOWN]:
        span = d.get("span") or {}
        where = span.get("file", "") + (":%d" % span["line"] if span.get("line") else "")
        out.append(f"  [{d.get('code')}] {d.get('message')}" + (f"  ({where})" if where else ""))
        if d.get("reason"): out.append(f"      why: {d['reason']}")
        fix = d.get("fix") or {}
        if fix.get("hint"): out.append(f"      fix: {fix['hint']}")
        if fix.get("replace") is not None: out.append(f"      replace with: {fix['replace']}")
    if len(errors) > MAX_SHOWN: out.append(f"  ... and {len(errors) - MAX_SHOWN} more")
    out.append("  full output: " + " ".join([*argv, *CHECK_ARGV, str(project)]))
    return "\n".join(out)

def main():
    try:
        event = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError, OSError):
        return 0
    edited = str((event.get("tool_input") or {}).get("file_path") or "")
    if not edited.endswith(WATCHED): return 0
    repo = Path(os.environ.get("CLAUDE_PROJECT_DIR") or event.get("cwd") or ".").resolve()
    project = enclosing_project(Path(edited).resolve(), repo)
    if project is None: return 0
    found = kernel(repo)
    if found is None: return 0
    argv, env = found
    try:
        r = subprocess.run([*argv, *CHECK_ARGV, str(project)], capture_output=True,
                           text=True, cwd=repo, env=env, timeout=300)
    except (OSError, subprocess.SubprocessError):
        return 0
    try:
        diagnostics = json.loads(r.stdout or "[]")
    except (json.JSONDecodeError, ValueError):
        if r.returncode == 0: return 0
        print((r.stdout + r.stderr).strip()[:4000], file=sys.stderr)
        return 2
    errors = [d for d in diagnostics if d.get("severity") == "error"]
    if not errors: return 0
    print(report(errors, Path(edited), project, argv), file=sys.stderr)
    return 2

if __name__ == "__main__":
    sys.exit(main())
